DROP TABLE IF EXISTS musteri CASCADE;

DROP TABLE IF EXISTS kullanici CASCADE;

DROP TABLE IF EXISTS dosya CASCADE;

CREATE TABLE musteri(
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        musteriadsoyad VARCHAR(100) NOT NULL,
                        email VARCHAR(50) NOT NULL


);

CREATE TABLE kullanici(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_adi VARCHAR(100) NOT NULL,
    kullanici_sifre VARCHAR(50) NOT NULL
);

CREATE TABLE dosya(
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          dosya_adi VARCHAR(100) NOT NULL,
                          musteri_id INT,
                          FOREIGN KEY (musteri_id) REFERENCES musteri (id)
);


INSERT INTO musteri(musteriadsoyad, email)
VALUES  ('BerkBalci','berkbalci1234@gmail.com'),
        ('MehmetYılmaz','mehmetyilmaz@gmail.com'),
        ('AliAydin','aliaydin@gmail.com'),
        ('MuratArabaci','muratarabaci@gmail.com');


INSERT INTO kullanici(kullanici_adi, kullanici_sifre)
VALUES ('rohanrider','101010');

INSERT INTO dosya(dosya_adi,musteri_id)
VALUES ('MyFile','1'),
       ('Photos','3'),
       ('Videos','2');